2st task
js-tasks-ru/js-20210921_sherzat-kozhoev pull request #2
Opened 2021-09-27 20:45 UTC by sherzatkozhoev

added implementation of function sortStrings, pick and omit

2021-09-27 20:46 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-09-28 12:19 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-09-28 12:35 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return param === 'desc' ? newArray.reverse() : newArray;
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2021-09-28 12:35 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    const charA = a[0];
не нужно сравнивать первые символы, `localeCompare` прекрасно умеет сравнивать строки целиком

2021-09-28 12:35 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  const result = {};
good 👍

2021-09-28 12:36 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  const result = {};
good 👍

2021-09-28 12:36 UTC, dosandk requested changes
решение `sortStrings` следует поправить

2021-09-28 13:00 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-09-30 13:27 UTC, dosandk approved these changes
good 👍

2021-09-30 13:28 UTC, merged